/*
 * TABLES DDL
 */

CREATE TABLE PRODUCT(
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(50),
    DESCRIPTION VARCHAR(50)
);

INSERT INTO PRODUCT(NAME,DESCRIPTION) VALUES('SOME NAME', 'SOME DESCRIPTION');
COMMIT;